#pragma once

#define EGOLIB_MATH_PRIVATE 1
#include "egolib/Math/Angle.hpp"
#include "egolib/Math/AABB.hpp"
#include "egolib/Math/Math.hpp"
#include "egolib/Math/ColourRgb.hpp"
#include "egolib/Math/ColourRgba.hpp"
#include "egolib/Math/ColourL.hpp"
#include "egolib/Math/ColourLa.hpp"
#include "egolib/Math/Cone3.hpp"
#include "egolib/Math/Convex.hpp"
#include "egolib/Math/Cube.hpp"
#include "egolib/Math/LERP.hpp"
#include "egolib/Math/Line.hpp"
#include "egolib/Math/Matrix.hpp"
#include "egolib/Math/Point.hpp"
#include "egolib/Math/Plane.hpp"
#include "egolib/Math/Random.hpp"
#include "egolib/Math/Sphere.h"
#include "egolib/Math/Standard.hpp"
#include "egolib/Math/Transform.hpp"
#include "egolib/Math/Vector.hpp"
#include "egolib/Math/VectorProjection.hpp"
#include "egolib/Math/VectorRejection.hpp"
#undef EGOLIB_MATH_PRIVATE
