# AppVeyor configuration for AppVeyor project "Egoboo".
clone_depth: 1

# Build worker image (VM template)
image: Visual Studio 2017

# Build branch "master" and "develop" only.
branches:
  only:
    - master
    - develop

platform:
    - Win32
    - x64
configuration:
    - Debug
    - Release

install:
  # depth 32 should be enough.
  - git submodule update --init --recursive --depth 32
  # Download and install CMake.
  - set CMAKE_URL="https://cmake.org/files/v3.30/cmake-3.30.0-windows-x86_64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

# Generate Visual Studio solution and projects.
before_build:
    #- nuget restore
    - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
    - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
    - cmake -G "%CMAKE_GENERATOR_NAME%" CMakeLists.txt

build:
    parallel: true                  # enable MSBuild parallel builds
    project: egoboo.sln             # path to Visual Studio solution

test_script:
    - ps: ctest --output-junit test-results-${env:APPVEYOR_JOB_ID}.xml -C ${env:CONFIGURATION} 
    - ps: |
        $webClient = New-Object 'System.Net.WebClient'
        $webClient.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results-${env:APPVEYOR_JOB_ID}.xml))

# if one matrix entry fails, all entries fails
# https://www.appveyor.com/docs/build-configuration#failing-strategy
matrix:
    fast_finish: true
