.PHONY: egolib egoboo clean
	
all: egolib egoboo

egolib:
	${MAKE} -C ./egolib -f Makefile.Windows

egoboo: egolib
	${MAKE} -C ./game -f Makefile.Windows
	
clean:
	${MAKE} -C ./egolib -f Makefile.Windows clean
	${MAKE} -C ./game -f Makefile.Windows clean
	